/**
 * API Generator
 *
 * Generates the ConstellationAPI class and TypeScript definitions
 * for Code Mode from existing MCP tool definitions.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import {
  toolNameToFunctionName,
  toolNameToTypeName,
  generateParameterType,
  jsonSchemaToTypeScript
} from './schema-to-typescript.js';
import { McpToolDefinition } from '../registry/McpToolDefinition.interface.js';
import { getToolRegistry } from '../registry/ToolRegistry.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Generate the complete Code Mode API from registered tools
 */
export async function generateCodeModeAPI(outputDir?: string) {
  const targetDir = outputDir || path.join(__dirname, '../../generated');

  // Ensure output directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const registry = getToolRegistry();
  const tools = registry.getAllTools();

  // Generate TypeScript definitions
  const typeDefinitions = generateTypeDefinitions(tools);
  fs.writeFileSync(
    path.join(targetDir, 'constellation-api.d.ts'),
    typeDefinitions
  );

  // Generate API class implementation
  const apiClass = generateApiClass(tools);
  fs.writeFileSync(
    path.join(targetDir, 'constellation-api.ts'),
    apiClass
  );

  // Generate helper utilities
  const helpers = generateHelpers();
  fs.writeFileSync(
    path.join(targetDir, 'code-mode-helpers.ts'),
    helpers
  );

  console.log(`Code Mode API generated successfully in ${targetDir}`);
  console.log(`  - constellation-api.d.ts: TypeScript definitions`);
  console.log(`  - constellation-api.ts: API class implementation`);
  console.log(`  - code-mode-helpers.ts: Helper utilities`);
}

/**
 * Generate TypeScript type definitions
 */
function generateTypeDefinitions(tools: McpToolDefinition[]): string {
  const lines: string[] = [
    '/**',
    ' * Constellation Code Mode API - Type Definitions',
    ' *',
    ' * Auto-generated TypeScript types for all MCP tools.',
    ' * DO NOT EDIT MANUALLY - Generated by api-generator.ts',
    ' */',
    '',
    '// Import base types from api-types',
    'import type {',
    '  SymbolInfo,',
    '  FileDetails,',
    '  Dependency,',
    '  DependencyNode,',
    '  CircularDependency,',
    '  UsageReference,',
    '  CallGraphNode,',
    '  OrphanedSymbol,',
    '  ImpactAnalysisResult,',
    '  ArchitectureOverview,',
    '} from "../types/api-types";',
    '',
    '// Tool Parameter Types',
    ''
  ];

  // Generate parameter types for each tool
  for (const tool of tools) {
    const paramTypeName = toolNameToTypeName(tool.name) + 'Params';
    const resultTypeName = toolNameToTypeName(tool.name) + 'Result';

    // Add tool documentation
    lines.push('/**');
    lines.push(` * Parameters for ${tool.name}`);
    lines.push(` * ${tool.shortDescription || tool.description}`);
    lines.push(' */');

    // Generate parameter interface
    const paramType = generateParameterType(tool.name, tool.inputSchema);
    lines.push(paramType);
    lines.push('');

    // Generate result type (mapped from api-types)
    lines.push('/**');
    lines.push(` * Result for ${tool.name}`);
    lines.push(' */');
    lines.push(`export interface ${resultTypeName} {`);

    // Map known result types based on tool name
    switch (tool.name) {
      case 'search_symbols':
        lines.push('  symbols: SymbolInfo[];');
        lines.push('  pagination?: { total: number; offset: number; limit: number; };');
        break;
      case 'get_symbol_details':
        lines.push('  symbol: SymbolInfo;');
        break;
      case 'get_dependencies':
      case 'get_dependents':
        lines.push('  dependencies: Dependency[];');
        lines.push('  totalCount: number;');
        break;
      case 'find_circular_dependencies':
        lines.push('  cycles: CircularDependency[];');
        lines.push('  totalCount: number;');
        break;
      case 'trace_symbol_usage':
        lines.push('  usages: UsageReference[];');
        lines.push('  totalUsages: number;');
        break;
      case 'get_call_graph':
        lines.push('  graph: CallGraphNode[];');
        lines.push('  totalNodes: number;');
        break;
      case 'find_orphaned_code':
        lines.push('  orphanedSymbols: OrphanedSymbol[];');
        lines.push('  totalCount: number;');
        break;
      case 'impact_analysis':
        lines.push('  impact: ImpactAnalysisResult;');
        break;
      case 'get_architecture_overview':
        lines.push('  overview: ArchitectureOverview;');
        break;
      default:
        lines.push('  data: any;');
    }

    lines.push('}');
    lines.push('');
  }

  // Generate main API interface
  lines.push('/**');
  lines.push(' * Constellation Code Mode API Interface');
  lines.push(' */');
  lines.push('export interface ConstellationAPI {');

  for (const tool of tools) {
    const functionName = toolNameToFunctionName(tool.name);
    const paramType = toolNameToTypeName(tool.name) + 'Params';
    const resultType = toolNameToTypeName(tool.name) + 'Result';

    // Add JSDoc
    lines.push('  /**');
    lines.push(`   * ${tool.shortDescription || tool.description}`);

    // Add example if available
    if (tool.examples && tool.examples.length > 0) {
      lines.push('   * @example');
      lines.push(`   * const result = await ${functionName}({`);
      const example = tool.examples[0];
      for (const [key, value] of Object.entries(example.parameters)) {
        const valueStr = typeof value === 'string' ? `"${value}"` : JSON.stringify(value);
        lines.push(`   *   ${key}: ${valueStr},`);
      }
      lines.push('   * });');
    }

    lines.push('   */');
    lines.push(`  ${functionName}(params: ${paramType}): Promise<${resultType}>;`);
    lines.push('');
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate the API class implementation
 */
function generateApiClass(tools: McpToolDefinition[]): string {
  const lines: string[] = [
    '/**',
    ' * Constellation Code Mode API - Implementation',
    ' *',
    ' * API class for Code Mode execution.',
    ' * DO NOT EDIT MANUALLY - Generated by api-generator.ts',
    ' */',
    '',
    'import type { ConstellationAPI } from "./constellation-api";',
    '',
    '/**',
    ' * API implementation that forwards calls to the MCP tool executor',
    ' */',
    'export class ConstellationAPIImpl implements ConstellationAPI {',
    '  constructor(',
    '    private executor: (toolName: string, params: any) => Promise<any>',
    '  ) {}',
    ''
  ];

  // Generate method implementations
  for (const tool of tools) {
    const functionName = toolNameToFunctionName(tool.name);
    const paramType = toolNameToTypeName(tool.name) + 'Params';
    const resultType = toolNameToTypeName(tool.name) + 'Result';

    lines.push(`  async ${functionName}(params: ${paramType}): Promise<${resultType}> {`);
    lines.push(`    return this.executor('${tool.name}', params);`);
    lines.push('  }');
    lines.push('');
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate helper utilities for Code Mode
 */
function generateHelpers(): string {
  return `/**
 * Code Mode Helper Utilities
 *
 * Utility functions and helpers for Code Mode scripts.
 * DO NOT EDIT MANUALLY - Generated by api-generator.ts
 */

import type { ConstellationAPI } from "./constellation-api";

/**
 * Workflow builder for chaining operations
 */
export class WorkflowBuilder {
  private steps: Array<() => Promise<any>> = [];
  private results: any[] = [];

  constructor(private api: ConstellationAPI) {}

  /**
   * Add a step to the workflow
   */
  step<T>(fn: (api: ConstellationAPI, previous: any) => Promise<T>): this {
    this.steps.push(async () => {
      const previous = this.results[this.results.length - 1];
      const result = await fn(this.api, previous);
      this.results.push(result);
      return result;
    });
    return this;
  }

  /**
   * Execute all steps in sequence
   */
  async execute(): Promise<any[]> {
    this.results = [];
    for (const step of this.steps) {
      await step();
    }
    return this.results;
  }

  /**
   * Get the last result
   */
  getLastResult(): any {
    return this.results[this.results.length - 1];
  }
}

/**
 * Pagination helper for iterating through paginated results
 */
export class PaginationHelper {
  constructor(
    private api: ConstellationAPI,
    private toolName: string
  ) {}

  /**
   * Fetch all pages of results
   */
  async fetchAll(params: any, maxPages: number = 10): Promise<any[]> {
    const allResults: any[] = [];
    let offset = 0;
    const limit = params.limit || 50;

    for (let page = 0; page < maxPages; page++) {
      const result = await (this.api as any)[this.toolName]({
        ...params,
        offset,
        limit
      });

      if (result.symbols) {
        allResults.push(...result.symbols);
        if (result.symbols.length < limit) break;
      } else if (result.dependencies) {
        allResults.push(...result.dependencies);
        if (result.dependencies.length < limit) break;
      } else {
        break;
      }

      offset += limit;
    }

    return allResults;
  }
}

/**
 * Filter builder for common query patterns
 */
export class FilterBuilder {
  private filters: Record<string, any> = {};

  /**
   * Filter by file pattern
   */
  inFiles(pattern: string): this {
    this.filters.filePattern = pattern;
    return this;
  }

  /**
   * Filter by symbol kind
   */
  ofKind(...kinds: string[]): this {
    this.filters.filterByKind = kinds;
    return this;
  }

  /**
   * Filter by export status
   */
  exported(isExported: boolean = true): this {
    this.filters.filterByExported = isExported;
    return this;
  }

  /**
   * Set pagination
   */
  paginate(limit: number, offset: number = 0): this {
    this.filters.limit = limit;
    this.filters.offset = offset;
    return this;
  }

  /**
   * Build the filter object
   */
  build(): Record<string, any> {
    return { ...this.filters };
  }
}

/**
 * Common analysis patterns
 */
export class AnalysisPatterns {
  constructor(private api: ConstellationAPI) {}

  /**
   * Find unused exports in the codebase
   */
  async findUnusedExports(): Promise<any[]> {
    const symbols = await this.api.searchSymbols({
      query: '',
      filterByExported: true,
      limit: 100
    });

    const usagePromises = symbols.symbols.map(s =>
      this.api.traceSymbolUsage({ symbolName: s.name, filePath: s.filePath })
    );

    const usages = await Promise.all(usagePromises);

    return symbols.symbols.filter((s, i) => usages[i].totalUsages === 0);
  }

  /**
   * Analyze refactoring impact
   */
  async analyzeRefactoringImpact(symbolName: string): Promise<any> {
    // Find the symbol
    const searchResult = await this.api.searchSymbols({
      query: symbolName,
      limit: 1
    });

    if (searchResult.symbols.length === 0) {
      return { error: 'Symbol not found' };
    }

    const symbol = searchResult.symbols[0];

    // Parallel analysis
    const [details, usage, impact] = await Promise.all([
      this.api.getSymbolDetails({
        symbolName: symbol.name,
        filePath: symbol.filePath
      }),
      this.api.traceSymbolUsage({
        symbolName: symbol.name,
        filePath: symbol.filePath
      }),
      this.api.impactAnalysis({
        symbolName: symbol.name,
        filePath: symbol.filePath
      })
    ]);

    return {
      symbol: details.symbol,
      usageCount: usage.totalUsages,
      impactSummary: impact.impact,
      riskLevel: this.calculateRiskLevel(usage.totalUsages, impact.impact)
    };
  }

  private calculateRiskLevel(usageCount: number, impact: any): string {
    if (usageCount > 50) return 'HIGH';
    if (usageCount > 20) return 'MEDIUM';
    if (usageCount > 5) return 'LOW';
    return 'MINIMAL';
  }
}

/**
 * Create helper instances for a Code Mode session
 */
export function createHelpers(api: ConstellationAPI) {
  return {
    workflow: () => new WorkflowBuilder(api),
    paginate: (toolName: string) => new PaginationHelper(api, toolName),
    filter: () => new FilterBuilder(),
    patterns: new AnalysisPatterns(api)
  };
}
`;
}

/**
 * Main CLI entry point for generating Code Mode API
 */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateCodeModeAPI()
    .then(() => console.log('✓ Code Mode API generation complete'))
    .catch((error) => {
      console.error('✗ Code Mode API generation failed:', error);
      process.exit(1);
    });
}