#!/bin/bash
# Constellation SessionStart Hook for Gemini CLI
# Generated by constellation-cli - DO NOT EDIT

cat << 'CONSTELLATION_EOF'
{
  "hookSpecificOutput": {
    "additionalContext": "You have Constellation access. `code_intel` is your PRIMARY tool for understanding this codebase—not an alternative, not a fallback, THE DEFAULT.\n\nMental model:\n- \"Where is X defined?\" → code_intel\n- \"What uses X?\" → code_intel\n- \"What would break?\" → code_intel\n- \"Find the string 'ERROR_CODE_123'\" → Grep\n\nGrep is for literal text. Everything else starts with code_intel."
  }
}
CONSTELLATION_EOF
