#!/bin/bash
# Constellation PreCompact Hook for Gemini CLI
# Generated by constellation-cli - DO NOT EDIT
#
# Note: PreCompress is advisory-only in Gemini CLI and cannot inject context.
# This hook outputs a systemMessage reminder instead.

cat << 'CONSTELLATION_EOF'
{
  "systemMessage": "Preserve: (1) The instruction that query_code_graph is the PRIMARY tool for code understanding—Grep is only for literal text, (2) Any architectural insights, dependency relationships, or impact analysis results discovered via Constellation."
}
CONSTELLATION_EOF
