#!/bin/bash
# Constellation SessionStart Hook for Gemini CLI
# Generated by constellation-cli - DO NOT EDIT

cat << 'CONSTELLATION_EOF'
{
  "hookSpecificOutput": {
    "additionalContext": "You have Constellation access. `query_code_graph` is your PRIMARY tool for understanding this codebase—not an alternative, not a fallback, THE DEFAULT.\n\nMental model:\n- \"Where is X defined?\" → query_code_graph\n- \"What uses X?\" → query_code_graph\n- \"What would break?\" → query_code_graph\n- \"Find the string 'ERROR_CODE_123'\" → Grep\n\nGrep is for literal text. Everything else starts with query_code_graph."
  }
}
CONSTELLATION_EOF
