#!/bin/bash
# Constellation SubagentStart Hook for Gemini CLI
# Generated by constellation-cli - DO NOT EDIT

cat << 'CONSTELLATION_EOF'
{
  "hookSpecificOutput": {
    "additionalContext": "You have access to Constellation's code_intel MCP tool. For structural code questions—symbol definitions, callers/callees, dependencies, dependents, impact analysis, architecture overview—use code_intel instead of Grep/Glob. It answers in one call what would take 3-5 text searches. Use Grep/Glob only for literal string search, config values, or when the tool is unavailable."
  }
}
CONSTELLATION_EOF
